- name: Installing httpd
  yum:
    name: httpd
    state: present
  
- name: start httpd
  service:
    name: httpd
    state: started
    
- name: configure index page
  copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: '0777'  
